### ISSUE TITLE
Tomcat 8 - resources not found

### ISSUE THREAD

**Issue by isuftin** [webjars/log4javascript#5] opened 2015-08-05 19:35 UTC
Testing with a fresh install of Tomcat 7 and Tomcat 8.

With tomcat 7, I am able to load log4javascript fine through the path: /webjars/log4javascript/1.4.13/log4javascript.js

With tomcat 8, this URL creates a 404.

Tomcat 7: Apache Tomcat/7.0.53
Tomcat 8: Apache Tomcat/8.0.24

Running on MacOS Yosemite 

I'm willing to provide log files if needed. I've looked around and could not find any issues with WebJars and Tomcat 8 specifically.

**Comment by jamesward** [comment] 2015-08-05 19:52
I've created a project with Tomcat 8 and I am unable to reproduce this.  Here is the project:
https://github.com/webjars/sample-tomcat

Can you see any differences between this and your setup that might be causing the issue?

**Comment by isuftin** [comment] 2015-08-05 19:56
I will test and report back. Thank you for the quick help.

**Comment by isuftin** [comment] 2015-08-05 19:58
@jamesward In your test project I don't specifically see that you are loading log4javascript. That's the only webjar I'm currently seeing an issue with. Are you able to successfully load log4javascript from webjars in-browser via Tomcat 8?

**Comment by jamesward** [comment] 2015-08-05 20:06
Yeah, I did test log4javascript and it loaded fine.

**Comment by isuftin** [comment] 2015-08-11 16:27
Strange. This is still not working for me.

I've uncommented log4js in the pom. I updated the index.jsp to show:

```
    <link rel='stylesheet' href='<%= org.webjars.AssetLocator.getWebJarPath("css/bootstrap.min.css") %>'>
    <script type='text/javascript' src='<%= org.webjars.AssetLocator.getWebJarPath("jquery.min.js") %>'></script>
    <script type='text/javascript' src='<%= org.webjars.AssetLocator.getWebJarPath("js/bootstrap.min.js") %>'></script>
    <script type='text/javascript' src='<%= org.webjars.AssetLocator.getWebJarPath("js/log4javascript.js") %>'></script>
```

I load the page once deployed and see:
![image](https://cloud.githubusercontent.com/assets/928288/9203291/e1c5fd4a-401b-11e5-8a39-ee79f13db330.png)

The URL it's attempting to access is: http://localhost:8080/sample-tomcat/webjars/log4javascript/1.4.13/js/log4javascript.js

**Comment by isuftin** [comment] 2015-08-11 16:30
It also seems to 404 on _lite.js and _production.js variants

**Comment by jamesward** [comment] 2015-08-11 16:41
I've created a branch that I've tested and it works for me: https://github.com/webjars/sample-tomcat/compare/master...log4javascript

**Comment by isuftin** [comment] 2015-08-11 16:42
@jamesward what version of tomcat on what OS and what flavor/version of Java?

**Comment by jamesward** [comment] 2015-08-11 18:57
That project uses Tomcat `8.0.23` via webapp-runner:
https://github.com/jsimone/webapp-runner/blob/tomcat8/pom.xml#L71

**Comment by isuftin** [comment] 2015-08-11 19:52
I'll give the webapp runner a shot to see if my deployment process. Currently Netbeans builds the project and deploys to a Tomcat 8 container.

**Comment by isuftin** [comment] 2015-08-12 14:47
@jamesward I haven't tried the runner yet but am also curious about the webjars locator project. In version 0.1 and 0.2 you had the AssetLocator.getWebJarPath() function but in later versions it disappeared. Is there an analog in the current version of the webjars-locator-core project that is an analog of this functionality? I am finding this very valuable. 

Also, do you have documentation on what we can do with the current webjars-locator project? It looks like it's been converted into a RequireJS configuration writer but I am not seeing any docs for it.

**Comment by davidmsibley** [comment] 2015-08-12 16:12
I've confirmed @isuftin 's issue, but I've also confirmed @jamesward 's.  log4javascript resolves when run using the webapp-runner, but if you drop the war into the webapps directory of an independent tomcat, it 404's.

One interesting tidbit is in https://github.com/davidmsibley/sample-tomcat 

When I misnamed the javascript resource in https://github.com/davidmsibley/sample-tomcat/commit/bb59bec2b9862eb19cbd8160008ad5344ef43948 `AssetLocator.getWebJarPath` returned null,  however when I corrected it in https://github.com/davidmsibley/sample-tomcat/commit/4ce0bd83a6db4fa971e9503a9a2ef1b394b37144 the correct url is constructed, but the url 404's when it's on an independent tomcat.

**Comment by jamesward** [comment] 2015-08-13 02:37
Sounds like we need to narrow down if this is an issue with `webjars-locator` / `webjars-locator-core`, an issue with Tomcat, or with the actual WebJar.  The sample project should help us narrow this down.

To narrow this down further we'd ideally have a reproducible test case.  The sample project could help us do that.  If we can match the environment where the bug occurs via a reproducible build then we can isolate where the bug is.

To answer @isuftin, the `webjars-locator` project has been split into two projects:
- `webjars-locator-core` = Utility that searches the CLASSPATH for WebJar assets allowing you to specify version-less paths
- `webjars-locator` = RequireJS addons on top of `webjars-locator-core`

**Comment by isuftin** [comment] 2015-08-13 13:18
@jamesward I'd suggest that the webjars-locator / core can be ruled out. This issue was experienced previous to me even knowing about the projects. 

Take a look here: https://github.com/isuftin/docker-webjars-test

I've made a Docker container that installs java, maven, pulls down a fresh copy of the latest Tomcat 8, pull down my fork of this repo which includes log4js in the pom and in the jsp and deploys it to Tomcat. I've tested this through the browser and this reproduces the issue.

If you have docker (and optionally docker-compose) installed, clone https://github.com/isuftin/docker-webjars-test, go to the directory you cloned it to and:

`$ docker-compose up`

Takes a while to build but once up, you should be able to go to `http://localhost:8080/sample-tomcat` and verify that the log4s webjar returns a 404 when requested

**Comment by isuftin** [comment] 2015-08-13 13:23
The other option is just to download tomcat from apache, run it and drop the war that the sample-tomcat project creates into it :)

**Comment by jamesward** [comment] 2015-08-13 16:40
Thanks for providing a reproducible test case for this.  I think this is something related to file permissions for the `log4javascript` WebJar.  I extracted the WebJar and then re-jar'd it and then it worked.  I'm perplexed as to why this works in my sample but not in yours.  But that must be some kind of Tomcat bug.

The thing that is different about this WebJar than others is that the original is a tar.gz not a zip.  And tar.gz files preserve file permissions where zips sometimes do.

So rather than try to narrow this down further I think the easiest fix will be to switch this WebJar to a zip source.  I'll see if that is an option...

**Comment by jamesward** [comment] 2015-08-13 16:47
I'm releasing `1.4.13-1` that is packaged from the zip.  @isuftin want to test that and reopen if it doesn't fix this?

**Comment by davidmsibley** [comment] 2015-08-13 17:39
my initial usage of the new release didn't fix the issue.  I'll go back through the docker example to confirm.

**Comment by isuftin** [comment] 2015-08-13 17:39
Same here. I will update the docker example to reflect the updated version.

**Comment by isuftin** [comment] 2015-08-13 17:57
Ok, I updated the tomcat-sample fork to reflect the latest log4js version so docker should pull that down when re-built.

**Comment by davidmsibley** [comment] 2015-08-13 19:02
@isuftin your docker-compose example wasn't working for me so I made some changes here: https://github.com/isuftin/docker-webjars-test/pull/1

**Comment by isuftin** [comment] 2015-08-14 11:50
@jamesward Also, I'm not sure that I can reopen this issue ;)

**Comment by jamesward** [comment] 2015-08-14 15:27
Thanks for testing this.  I was wrong about file permissions.  After further testing this is actually due to the file name of the jar.  WTF.  When I repackaged the jar I had also changed the name.  I didn't think this would have an impact but...

I've narrowed the issue down to the name of the jar beginning with `log`.  So for some reason Tomcat ignores jars in `WEB-INF/lib` that begin with `log`.  Wowsers.  Lets see if we can find a workaround...

**Comment by jamesward** [comment] 2015-08-14 15:43
I think the best solution is to rename this with your own build.  Here are some options for that: https://stackoverflow.com/questions/4969313/renaming-maven-dependency-in-wars-web-inf-lib-folder

Someone could probably scour the Tomcat source and find the root of this.  But I'm going to guess there is some legacy reason for this behavior and they won't fix it.

**Closed by jamesward** 2015-08-14 15:43 UTC

**Comment by markt-asf** [comment] 2015-08-14 16:46
I suspect this is fixable with a minor configuration tweak. If it is, I can get that necessary change into the next Tomcat release.

By default, Tomcat ignores most JARs named log4j\* when scanning for SCIs, annotations etc. There are explicit exceptions defined in $CATALINA_BASE/conf/catalina.properties. Try adding the JAR (or a suitable pattern) to the tomcat.util.scan.StandardJarScanFilter.jarsToScan property in that file.

If this fixes it then just let me know what pattern needs to be added and I'll get that done. If it doesn't point me towards the test WAR (it wasn't clear to me where to find it reading through this issue) and I'll dig deeper.

**Comment by jamesward** [comment] 2015-08-14 19:06
Thanks @markt-asf for the details.

**Comment by isuftin** [comment] 2015-08-17 12:22
@markt-asf I removed "log4j*.jar" from the "tomcat.util.scan.StandardJarScanFilter.jarsToSkip" list and this fixes the issue.

I also tried adding "log4javascript*.jar" to the tomcat.util.scan.StandardJarScanFilter.jarsToScan list, which also fixes the issue.

**Comment by jamesward** [comment] 2015-08-17 12:50
Thanks @isuftin!  I figured this would cause some kind of regression.  But glad to see the removal of this special case.

**Comment by markt-asf** [comment] 2015-08-17 13:36
I'll get log4javascript*.jar added to the jarsToScan list for the next round of releases.
